Make CI fail if there are clang format errors

diff --git a/eng/pipelines/templates/jobs/archetype-sdk-client.yml b/eng/pipelines/templates/jobs/archetype-sdk-client.yml
--- a/eng/pipelines/templates/jobs/archetype-sdk-client.yml
+++ b/eng/pipelines/templates/jobs/archetype-sdk-client.yml
@@ -111,6 +111,27 @@ jobs:
     # It is 'enabled' by default on linux-gcc but it can be opt-out by each pipeline (disabled) 
     condition: and(succeededOrFailed(), ne(variables['CODE_COVERAGE'], 'disabled'), ne(variables['CODE_COVERAGE'], ''))
 
+  # Validate all the files are formatted correctly according to the .clang-format file.
+  - bash: |
+      # Run clang-format recursively on each source and header file within the repo sdk folder.
+      find sdk/ -regex '.*\.\(cpp\|hpp\)' -exec clang-format -style=file -i {} \;
+
+      if [[ `git status | grep modified | awk '{print $2}'` ]]; then
+        echo Some files were not formatted correctly according to the .clang-format file.
+        echo Please run clang-format to fix the issue by using this bash command at the root of the repo:
+        echo "find sdk/ -regex '.*\.\(cpp\|hpp\)' -exec clang-format -style=file -i {} \;"
+        echo ""
+        echo "List of files missing format:"
+        git status | grep modified | awk '{print $2}'
+        exit 1
+      fi
+
+      echo Success, all files are formatted correctly according to the .clang-format file.
+      exit 0
+
+    displayName: Validate Clang Format
+    condition: and(succeededOrFailed(), ne(variables['CODE_COVERAGE'], 'disabled'), ne(variables['CODE_COVERAGE'], ''))
+
   - template: /eng/pipelines/templates/steps/cmake-build.yml
     parameters:
       GenerateArgs: "$(CmakeArgs)"
